#!/usr/bin/env python3
"""Minest Desktop Pet: rebuild Resources/Web from the current iPhone build.

The desktop pet runs the web Mini Pet's own code (so the two never drift apart). This copies, from
the iPhone page, the Mini Pet core and its behaviour script (reactions, menu bubbles, tips, inbox,
Octo mirroring), wraps them with the desktop host + bridge (web-src/), and copies three.js r128,
GLTFLoader, cosmetics-v1.js and the model next to it.

Run after every change to the web Mini Pet:   python3 macos/MinestDesktopPet/sync-web.py [iPhoneX.Y.html]
then ./build.sh to rebuild the app.
"""
import glob, os, re, shutil, sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(HERE, 'Resources', 'Web')
SRC = os.path.join(HERE, 'web-src')


def latest_iphone():
    def ver(p):
        m = re.match(r'iPhone(\d+)\.(\d+)\.html$', os.path.basename(p))
        return (int(m.group(1)), int(m.group(2))) if m else (-1, -1)
    files = [p for p in glob.glob(os.path.join(REPO, 'iPhone*.html')) if ver(p)[0] >= 0]
    return max(files, key=ver)


def script_from(html, marker):
    """The body of the <script> block whose code starts with `marker`."""
    i = html.index(marker)
    start = html.rindex('<script>', 0, i) + len('<script>')
    end = html.index('</script>', i)
    return html[start:end].strip('\n')


def main():
    page = sys.argv[1] if len(sys.argv) > 1 else latest_iphone()
    page = page if os.path.isabs(page) else os.path.join(REPO, page)
    html = open(page, encoding='utf-8').read()
    core = script_from(html, '/* 41.377 Mini Pet P0:')
    behaviour = script_from(html, '/* 44.5 Pet rewards:')
    for need in ('window.__miniPetHost', 'window.__miniPetCtl'):
        if need not in core:
            sys.exit('The Mini Pet core in %s has no %s — build from 44.6 or later.' % (os.path.basename(page), need))

    os.makedirs(os.path.join(OUT, 'vendor'), exist_ok=True)
    os.makedirs(os.path.join(OUT, 'models'), exist_ok=True)
    copies = [
        (os.path.join(REPO, 'ios', 'Minest', 'Minest', 'vendor', 'three.min.js'), os.path.join(OUT, 'vendor', 'three.min.js')),
        (os.path.join(REPO, 'ios', 'Minest', 'Minest', 'vendor', 'GLTFLoader.js'), os.path.join(OUT, 'vendor', 'GLTFLoader.js')),
        (os.path.join(REPO, 'octopus-pet-raising-v6', 'cosmetics-v1.js'), os.path.join(OUT, 'cosmetics-v1.js')),
        (os.path.join(REPO, 'octopus-pet-raising-v6', 'models', 'avatar_web_rigged_v23j.glb'), os.path.join(OUT, 'models', 'avatar_web_rigged_v23j.glb')),
    ]
    for a, b in copies:
        shutil.copyfile(a, b)
    old = os.path.join(OUT, 'models', 'avatar_web_rigged_v23.glb')   # the 6.6 MB model is no longer used
    if os.path.exists(old):
        os.remove(old)

    host = open(os.path.join(SRC, 'desktop-host.js'), encoding='utf-8').read()
    bridge = open(os.path.join(SRC, 'desktop-bridge.js'), encoding='utf-8').read()
    name = os.path.basename(page)
    doc = '\n'.join([
        '<!doctype html>',
        '<html lang="en">',
        '<head>',
        '<meta charset="utf-8">',
        '<meta name="viewport" content="width=device-width, initial-scale=1">',
        '<title>Minest Desktop Pet</title>',
        '<!-- GENERATED by sync-web.py from %s — edit the iPhone page or web-src/, not this file -->' % name,
        '<script>\n' + host + '</script>',
        '<script src="vendor/three.min.js"></script>',
        '<script src="vendor/GLTFLoader.js"></script>',
        '<script src="cosmetics-v1.js"></script>',
        '</head>',
        '<body>',
        '<script>\n' + bridge + '</script>',
        '<script>\n/* ---- Mini Pet core, from %s ---- */\n' % name + core + '\n</script>',
        '<script>\n/* ---- Mini Pet behaviour, from %s ---- */\n' % name + behaviour + '\n</script>',
        '<script>try { window.webkit.messageHandlers.desktopPet.postMessage({ type: "ready", source: "%s" }); } catch (e) {}</script>' % name,
        '</body>',
        '</html>',
        ''
    ])
    open(os.path.join(OUT, 'index.html'), 'w', encoding='utf-8').write(doc)
    print('Desktop pet web rebuilt from %s → %s (%d KB)' % (name, OUT, len(doc) // 1024))


if __name__ == '__main__':
    main()
